### ISSUE TITLE
Example doesn't work with Turbopack

### ISSUE THREAD

**Issue by gstrobl** [i18next/next-app-dir-i18next-example-ts#11]
## 🐛 Bug Report

If you want to run this solution with Turbopack, the i18n-next doesn't work. It always selects the the first language in the folder structure of the imports.
## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
next dev --turbo
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *i18next version*: i.e. 23.9.0
- *os*: Mac

**Comment by adrai** [comment]
don't know what you mean, I just updated this example and seems to work with turbo...

If you mean next-i18next => you may have a look at: https://github.com/i18next/next-i18next/issues/2222

**Comment by gstrobl** [comment]
https://github.com/i18next/next-app-dir-i18next-example-ts/assets/8993732/7860eac5-e6c1-4385-bb79-182bcb4f7555

On my machine it doesn't work, if I remove the turbo flag it's working.
