### ISSUE TITLE
If I move the app into the src directory, the homepage will display 404

### ISSUE THREAD

**Issue by aboutjquery** [i18next/next-app-dir-i18next-example-ts#12]
```js
import { fallbackLng, languages, cookieName } from './src/app/i18n/settings'
```

## Expected behavior

If my app is moved into the src directory, 404 will be displayed on the homepage. I have changed the i18n setting path of middleware.ts, and 404 will appear on the homepage. If I add /en, it will display normally, but if I don’t add en, 404 will appear.

**Comment by adrai** [comment]
Is app in src supported by Next.js? https://nextjs.org/docs/app

**Comment by aboutjquery** [comment]
> Is app in src supported by Next.js? https://nextjs.org/docs/app

I believe it is. In the latest nextjs 14.x, when creating a project, there is also a question whether to create a src directory, and my other functions are all normal in src/app.

https://nextjs.org/docs/app/building-your-application/configuring/src-directory

**Comment by adrai** [comment]
Are you sure you've also moved the middleware.ts file in to the src folder?
I just tried to move the app folder into the src folder and also the middleware.ts into the src folder and it works...

https://nextjs.org/docs/app/building-your-application/configuring/src-directory
<img width="679" alt="image" src="https://github.com/i18next/next-app-dir-i18next-example-ts/assets/1086194/14d1fe39-0b38-4d30-83fb-212eeebac855">

**Comment by aboutjquery** [comment]
> Are you sure you've also moved the middleware.ts file in to the src folder? I just tried to move the app folder into the src folder and also the middleware.ts into the src folder and it works...
> 
> https://nextjs.org/docs/app/building-your-application/configuring/src-directory <img alt="image" width="679" src="https://private-user-images.githubusercontent.com/1086194/344044992-14d1fe39-0b38-4d30-83fb-212eeebac855.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NTMyMzEsIm5iZiI6MTcxOTU1MjkzMSwicGF0aCI6Ii8xMDg2MTk0LzM0NDA0NDk5Mi0xNGQxZmUzOS0wYjM4LTRkMzAtODNmYi0yMTJlZWViYWM4NTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMDUzNTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzY0MDVmODdmZmI1NGNiNTI2YTc4MTgxNzZkMDFhYzMwM2FkYzkzYTg3NGIwNGYwMDk1NTVjYmQxOTRjMjBmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tc2Ps_FClWrH4tyQBIYzRuQ1Nqg7bL1kmUOCf7beCJo">

That's the problem, thank you.
