### ISSUE TITLE
i18next type-safe intelligence is not working with i18next@23.4.6, but it works with i18next@22.4.14.

### ISSUE THREAD

**Issue by ShihTingJustin** [i18next/next-app-dir-i18next-example-ts#4]
## 🐛 Bug Report

I found that type-safe intelligence is not working with i18next@23.4.6 after cloned this sample repo and installed it.
![image](https://github.com/i18next/next-13-app-dir-i18next-example-ts/assets/56827791/c592bd1a-5c11-4854-aa30-0fa721a82048)

But it works with i18next@22.4.14.

![image](https://github.com/i18next/next-13-app-dir-i18next-example-ts/assets/56827791/295bf46f-9c3e-45a3-8f63-e424cebc11e7)

## To Reproduce

```
npm i i18next@23.4.6
```
```
npm i i18next@22.4.14
```

## Expected behavior
Using i18n key with type-safe intelligence.

## Your Environment

- *runtime version*: node v18.12.1
- *i18next version*: 23.4.6
- *os*: Windows 10

**Comment by adrai** [comment]
Which editor do you use?
Make sure you update your typescript dependency: https://github.com/i18next/react-i18next/issues/1666

**Comment by ShihTingJustin** [comment]
> Which editor do you use? Make sure you update your typescript dependency: [i18next/react-i18next#1666](https://github.com/i18next/react-i18next/issues/1666)

I used VS Code@1.73.0, and typescript@5.1.6 (as same as this repo) at first.
After I update to VS Code@1.81.1 and it works!
