### ISSUE TITLE
useTranslation without passing the lang param

### ISSUE THREAD

**Issue by NourAlzway** [i18next/next-app-dir-i18next-example-ts#6]
how to use the `useTranslation` without passing the lang param every time you want to use it, for example, if you have nested components like this
- ExplorePage.tsx
  - Filter.tsx
    - Actions.tsx
      - SubmitButton.tsx  
      
and you want to use `useTranslation` in the `SubmitButton.tsx`, but you don't have the lang param if you don't drill down the props.

**Comment by adrai** [comment]
not possible right now without lng... and depending on if its client or server side, also a react context can't be used...

**Comment by adrai** [comment]
Here an alternative: https://github.com/i18next/next-app-dir-i18next-no-locale-path-example
