### ISSUE TITLE
Some translations in Next app not working

### ISSUE THREAD

**Issue by nareshbhatia** [i18next/next-app-dir-i18next-example-ts#8]
## 🐛 Bug Report

I have implemented 6 translations in my app using the guidance in this example: en, de, ar, es, hi, it. Only en & de are working. When I switch to the other 4, the page shows English – the translations are not being picked up. There is nothing special about the setup for these 4 languages. They are identical to English & German setup.

## To Reproduce

A [minimal reproducible example](https://github.com/nareshbhatia/i18n-demo). Please see README for build instructions.

## Expected behavior

All languages should translate correctly.

## Your Environment

- *runtime version*: i.e. node v20, Chrome latest
- *i18next version*: 23.9.0 (latest)
- *os*: Mac

**Comment by adrai** [comment]
just rename the translation files:
<img width="377" alt="image" src="https://github.com/i18next/next-app-dir-i18next-example-ts/assets/1086194/da0df312-1d3b-4237-b3a7-a2cb15dc194b">

it's translation.json not translations.json

**Comment by nareshbhatia** [comment]
OMG! I feel so silly. Thank you so much for pointing this out, @adrai.
