### ISSUE TITLE
Content inside public folder is not accessible

### ISSUE THREAD

**Issue by janoschp** [i18next/next-app-dir-i18next-example-ts#9]
I reproduced this in your project, checked it out, ran it and tried to access localhost:3000/site.webmanifest , it re-directs to /en/site.webmanifest which is a 404 page.

**Comment by adrai** [comment]
adapt the middleware to your needs: https://github.com/i18next/next-app-dir-i18next-example-ts/blob/main/middleware.ts

**Comment by adrai** [comment]
<img width="811" alt="image" src="https://github.com/i18next/next-app-dir-i18next-example-ts/assets/1086194/c9ed9bfb-655f-437b-b0da-9efad865a695">
